export const accordionData = [
  {
    title: "J'ai un Bac",
    content: `Si vous avez un BAC, quelque soit votre Série, vous devez faire des Etudes Supérieures. Nous vous conseillons le BACHELOR (Licence Américaine, BAC+3) en IMS (Gestion des Systèmes Informatiques) qui va faire de vous Un Informaticien Complet .Ce programme complètement révolutionnaire combine la Sécurité, Hacking, Dépannage, Maintenance, Management des Systèmes Informatiques, Réseaux, Administration de Serveurs et Cloud, Programmation, et + de 40 Certifications Américaines. Vous devenez en 3ans le Spécialiste que toutes les entreprises recherchent!`,
  },
  {
    title: "J'ai un BTS / BAC + 2",
    content: `Pour ceux des Filières Industrielles Réseaux...Faites le meilleur choix entre ces 3: + Vous pouvez choisir de faire des Etudes Supérieures. Nous vous conseillons un MASTER (BAC+5) en CLOUD qui va faire de vous un vrai DSI - Directeur des Systèmes Informatiques car il combine les notions rares et avancées de la  Sécurité, Hacking, Maintenance et Dépannage à distance, Management des Systèmes Informatiques et Gestion des Projets, Réseaux, Administration Avancée de Serveurs et Cloud, et + de 40 Certifications Américaines) - Durée: 3 ans avec votre BTS/Bac+2. || + Vous pouvez opter pour le Programme Spécial Equivalence Américaine CISCO qui permet d’obtenir une Bourse pour suivre une Spécialisation Américaine de Technicien, Administrateur ou Professionnel des Réseaux CISCO en suivant une formation pratique dans le Laboratoire de l’Université Indienne à Abidjan, NYS-AFRICA. || + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée). 
    Pour ceux des Filières Industrielles Développement, Programmation Faites le meilleur choix entre ces 3: + Vous pouvez opter pour des Etudes Supérieures : MASTER (BAC+5) en DATA SCIENCE qui fait de vous un Programmeur Senior et combine les programmes extrêmement rares de la Sécurité Avancée, Hacking Avancé, Management des Systèmes Informatiques et Gestion des Projets, Programmation Avancée, Business Intelligence, Data Science, et + 40 Certifications Américaines) - Durée: 3 ans avec votre BTS/Bac+2 || + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée) Pour ceux des Filières Tertiaires : + Profitez du Programme Spécial CHLOE 2020 qui permet d’obtenir une Bourse pour suivre une Spécialisation Américaine de Technico-Commercial et combine la Spécialité de Stratégiste Digital/Communication et Créatif avec une maitrise des Technologies Nouvelles et de la Sécurité Informatique || + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée)`,
  },
  {
    title: "J'ai une licence / BAC + 3",
    content: `Pour ceux des Filières Industrielles Réseaux : + Vous pouvez choisir de faire des Etudes Supérieures. Nous vous conseillons un MASTER (BAC+5) en CLOUD qui fait de vous un vrai DSI - Directeur des Systèmes Informatiques car il combine les notions rares et avancées de la  Sécurité, Hacking, Maintenance et Dépannage à distance, Management des Systèmes Informatiques et Gestion des Projets, Réseaux, Administration Avancée de Serveurs et Cloud, et + de 40 Certifications Américaines) - Durée: 2 ans avec votre Bac+3 || + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée). Pour ceux des Filières Industrielles Développement, Programmation || + Vous pouvez opter pour des Etudes Supérieures. Nous vous conseillons un MASTER (BAC+5) en DATA SCIENCE qui fait de vous un Programmeur Senior et combine les programmes extrêmement rares de la Sécurité Avancée, Hacking Avancé, Management des Systèmes Informatiques et Gestion des Projets, Programmation Avancée, Business Intelligence, Data Science, et + 40 Certifications Américaines) - Durée: 2 ans avec votre Bac+3 || + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée). Pour ceux des Filières Tertiaires || + Profitez du Programme Spécial CHLOE 2020 qui permet d’obtenir une Bourse pour suivre une Spécialisation Américaine de Technico-Commercial et combine la Spécialité de Stratégiste Digital/Communication et Créatif avec une maitrise des Technologies Nouvelles et de la Sécurité Informatique) || + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée)`,
  },
  {
    title: "J'ai un diplôme d'ingénieur / BAC + 4,5",
    content: `Pour ceux des Filières Industrielles + Vous devez suivre une Certification Américaine orientée Entreprise (courte durée) Pour ceux des Filières Tertiaires + Vous pouvez opter pour le Programme Spécial CHLOE 2020 qui permet d’obtenir une Bourse pour suivre une Spécialisation Américaine de Technico-Commercial et combine la Spécialité de Stratégiste Digital/Communication et Créatif avec une maitrise des Technologies Nouvelles et de la Sécurité Informatique + Vous pouvez aussi opter pour des Certifications Américaines orientées Entreprise (courte durée)`,
  },
  {
    title: "Je n'ai pas de diplôme",
    content: `Même sans diplôme, vous pouvez suivre une Spécialisation qui vous donnera une Carrière, avec les Certifications Américaines orientées Entreprise (courte durée)`,
  },
];
